version: '3.1'

services:
    delta:
        image: delta
        build: .
        environment:
            NODE_ENV: production
        ports:
            - 3000:3000
    redis:
        image: redis
        command: ['redis-server', '--bind', 'redis', '--port', '6379']
